### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by jieun419** [jieun419/preproject-todo-app#1]
### 만들고자 하는 기능이 무엇인가?
- Todo 생성 기능

### 해당 기능을 구현하기 위해 할 일이 무엇인가?
- [x] Todo 입력폼 구현
- [x] 입력 시 화면에 노출
- [x] 새로고침 시 리스트 노출 되도록 localStorage에 저장하기

### 예상 작업 시간
- 6h
